name: Trigger Helm Chart
on:
  [push, workflow_dispatch]
permissions:
  id-token: write
  contents: read
jobs:
  run-my-action:
    name: Trigger Helm Chart
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Action
        uses: actions/checkout@v3
#      - name: Checkout and Run Custom Image Action
#        uses: Q6Cyber/helm-chart-trigger-workflow@v1.0.0
      - name: Get composite run steps repository
        uses: actions/checkout@v3
        with:
          repository: Q6Cyber/helm-chart-trigger-workflow
          # Select revision (The relaese of the app above)
          ref: v1.0.1
          # Personal access token to check out private repository
          token: ${{ secrets.GIT_TOKEN }}
          # Indicate where to check action out to
          path: ./
      - uses: ./helm-chart-trigger-workflow
        with:
          array-json: '[
                        {
                          "env": "prod",
                          "application": "dataflow",
                          "tag": "carls-test",
                          "image": "carls-image",
                          "imageKey": "deployment.image",
                          "valuesParentFolder": "bdu",
                          "misc": [
                            {
                              "key": "blah.blah",
                              "value": "blahhhhhhh"
                            },
                            {
                              "key": "blah.blah",
                              "value": "blahhhhhhh"
                            }
                          ]
                        },
                        {
                          "env": "prod",
                          "application": "dataflow",
                          "tag": "carls-test",
                          "image": "carls-image",
                          "imageKey": "deployment.image",
                          "valuesParentFolder": "bnr",
                          "misc": [
                            {
                              "key": "blah.blah",
                              "value": "blahhhhhhh"
                            },
                            {
                              "key": "blah.blah",
                              "value": "blahhhhhhh"
                            }
                          ]
                        },
                        {
                          "env": "prod",
                          "application": "dataflow",
                          "tag": "carls-test",
                          "image": "carls-image",
                          "imageKey": "deployment.image",
                          "valuesParentFolder": "cards",
                          "misc": [
                            {
                              "key": "cards",
                              "value": "blahhhhhhh"
                            },
                            {
                              "key": "dude",
                              "value": "blahhhhhhh"
                            }
                          ]
                        }
                      ]'

