name: Trigger Helm Chart
on:
  [push, workflow_dispatch]
jobs:
  run-my-action:
    name: Trigger Helm Chart
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get composite run steps repository
        uses: actions/checkout@v3
        with:
          # action file is located in another repo called workflows at /workflows/actions/action.yaml
          repository: Q6Cyber/helm-chart-trigger-workflow
          #  ref: mybranch  # in case it's not master branch
          # use deploy key instead of personal access token
          # see if i can get around this
          # need this token: '${{ github.token }' fpr repos not in the actions thing
#          ssh-key: ${{ secrets.WORKFLOWS_DEPLOYMENT_KEY }}
          array-json: '[
                        {
                          "env": "prod",
                          "application": "dataflow",
                          "tag": "carls-test",
                          "image": "carls-image",
                          "imageKey": "deployment.image",
                          "valuesParentFolder": "bdu",
                          "misc": [
                            {
                              "key": "blah.blah",
                              "value": "blahhhhhhh"
                            },
                            {
                              "key": "blah.blah",
                              "value": "blahhhhhhh"
                            }
                          ]
                        },
                        {
                          "env": "prod",
                          "application": "dataflow",
                          "tag": "carls-test",
                          "image": "carls-image",
                          "imageKey": "deployment.image",
                          "valuesParentFolder": "bnr",
                          "misc": [
                            {
                              "key": "blah.blah",
                              "value": "blahhhhhhh"
                            },
                            {
                              "key": "blah.blah",
                              "value": "blahhhhhhh"
                            }
                          ]
                        },
                        {
                          "env": "prod",
                          "application": "dataflow",
                          "tag": "carls-test",
                          "image": "carls-image",
                          "imageKey": "deployment.image",
                          "valuesParentFolder": "cards",
                          "misc": [
                            {
                              "key": "cards",
                              "value": "blahhhhhhh"
                            },
                            {
                              "key": "dude",
                              "value": "blahhhhhhh"
                            }
                          ]
                        }
                      ]'
